# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-reports
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image and push to Docker Hub
          command: |
            set -x
            cd build/ci
            TAG="${CIRCLE_TAG}.${CIRCLE_BUILD_NUM}"
            sed -i 's/$TAG/'"$TAG"'/g' docker-compose.yml
            docker-compose build
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker tag jpparker/national-lottery-picker:$TAG jpparker/national-lottery-picker:latest
            docker push jpparker/national-lottery-picker:$TAG
            docker push jpparker/national-lottery-picker:latest

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
