national-lottery:
  game: "euromillions"
  numberOfTickets: 1
  days: ["tue", "fri"]
  username: "username"
  password: "password"
  costLimit: 5.0
app:
  debug: true
  logfile: "/var/log/national-lottery-picker.log"
  screenshotDir: "/var/tmp"
