national-lottery:
  draw: "euromillions"
  numberOfTickets: 1
  days: ["tue", "fri"]
  username: "username"
  password: "password"
  costLimit: 5.0
app:
  debug: true
  logdir: "/var/log/national-lottery-picker"
  screenshotDir: "/var/tmp"
