national-lottery:
  draws:
    - name: "euromillions"
      numberOfTickets: 1
      day: "tue"
  username: "username"
  password: "password"
  costLimit: 10.0
app:
  debug: true
  logfile: "/var/log/national-lottery-picker.log"
  screenshotDir: "/var/tmp"
